spring:
  datasource:
#    url: jdbc:postgresql://${DB_HOST:city-report-db}:${DB_PORT:5432}/${DB_NAME:city_report_db}
#    username: ${DB_USERNAME:postgres}
#    password: ${DB_PASSWORD:postgres}
    url: jdbc:postgresql://localhost:5432/city_report_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.spatial.dialect.postgis.PostgisPG10Dialect
        format_sql: true

  flyway:
    enabled: true

  mail:
    host: localhost
    port: 1025
    properties:
      mail.smtp.auth: false
      mail.smtp.starttls.enable: false

cloudinary:
  cloud-name: dohsfqs6d
  api-key: 123894699435121
  api-secret: iUwG2F8x45rHmXBMDSLBcXwoyQg

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger
    operationsSorter: method
    tagsSorter: alpha
  show-actuator: false